apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-aws-proxy
  namespace: domino-compute
  labels:
    app: mlflow-aws-proxy
    tt: t
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-aws-proxy
  template:
    metadata:
      labels:
        app: mlflow-aws-proxy
    spec:
      containers:
        - name: mlflow-aws-proxy
          image: quay.io/wadkars/mock-jit:awsv3
          env:
            - name: DOMINO_ADMIN_API_KEY
              value: 412748c2003ff293acc416f53b3e9e6af8cb968cd91b1df4fc89c4e7c4105701
          ports:
            - containerPort: 6010